### PR TITLE
fix 32u4 and Feather M0 entries; fix line endings

### PR DESCRIPTION
**Pull request by dhalbert**
Circuit Playground Classic was failing to be seen by the code.org Maker App, and by Arduino on Win7. This was due to `&MI_00` being introduced on the 32u4 bootloader entries in 2.3.0, :face_with_head_bandage:  e.g.:
```
"%CIRCUIT_PLAYGROUND% Bootloader (0011)"=DriverInstall, USB\VID_239A&PID_0011&MI_00
```
These `&MI_00` additions were removed for CPC, Flora, Bluefruit Micro, and Feather 32u4. Retested with Arduino and code.org Maker App.

Also I made sure the .inf files all have CRLF line endings.

Problem found by forum user: https://forums.adafruit.com/viewtopic.php?f=48&t=142067. I'm surprised this wasn't found earlier, but there may be very few new Win7 code.org users since the new drivers were released in July.

I've put a signed `adafruit_drivers_2.3.2.0.exe` in a non-public draft release for testing convenience: 
https://github.com/adafruit/Adafruit_Windows_Drivers/releases/download/untagged-f6d096ac4b0c6c089dbc/adafruit_drivers_2.3.2.0.exe

### CODE REVIEW

**Comment by dhalbert** [comment]
Working on another set of fixes for non-Express boards with UF2 bootloaders, so hold off on merging this.

**Comment by dhalbert** [comment]
cda16f fixes https://forums.adafruit.com/viewtopic.php?f=57&t=142288; tested by forum poster.

**Comment by dhalbert** [comment]
@ladyada you did merge this! Sorry! I missed the email about it. I'll make a release right now.

**Comment by ladyada** [comment]
oh yay go me :D

**Pull request merged**
