### PR TITLE
Add Feather M0 and M4 Express CircuitPython PIDs; add pIRKey PIDs; other minor fixes

### PR DESCRIPTION
**Pull request by dhalbert**
Old Crow (@cs80) cold not install a CircuitPython Feather M0 Express on his Win7 machine. Added the correct USB PID entries. Also added entries for FM4X CircuitPython, and made a few of the labels more consistent.

### CODE REVIEW

**Comment by dhalbert** [comment]
Hi @ladyada - ping for a new driver build. Another Feather M0 Express user caught in this trap: https://forums.adafruit.com/viewtopic.php?f=57&t=130393. If you are up to your ears, I can build and try signing.

**Comment by ladyada** [comment]
yah please try, i can do if you get stuck its ez

**Comment by dhalbert** [comment]
@ladyada Added pIRKey to this PR, which previously added missing Feather M0 and M4 Express CircuitPython PIDs. Signed. Test installer at https://github.com/adafruit/Adafruit_Windows_Drivers/releases/tag/2.2.0. Do you want to test before merging and publishing release?

**Comment by ladyada** [comment]
just tested it with pirkey and its good and all signatures worked out so i think its gooood!

**Pull request merged**
